In [1]:
import numpy as np

In [10]:
arr = np.array([[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]]])
print(arr, arr.shape, arr.dtype)

#indexing
print(arr[0, 1, 1]) #4
print(arr[1, 1, 0]) #9

#slicing
print(arr[:, 0, :])
print(arr[:, :, 0])

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2) int64
4
9
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]
