In [10]:
import numpy as np
from numpy import dtypes

In [14]:
#properties
arr1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr1.shape) #dimensions
print(arr1.dtype) #data type
print(arr1.size) #no of elements
print(arr1.ndim) #number of dimensions

float_arr = arr1.astype(float)
print(float_arr, float_arr.dtype)

(3, 3)
int64
9
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64
