In [18]:
import numpy as np

In [19]:
#operations
arr1 = np.array([[1,2,3], [4,5,6]])
print(arr1.shape)

reshaped_arr = arr1.reshape((6,1))
print(reshaped_arr, reshaped_arr.shape)

flattened_arr = arr1.flatten()
print(flattened_arr, flattened_arr.shape)

(2, 3)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] (6, 1)
[1 2 3 4 5 6] (6,)


In [20]:
#indexing
arr2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr1[1, 2])

6


In [21]:
#fancy indexing
arr3 = np.array([1,2,3,4,5])
idx = [1,2,4]
print(arr3[idx])

[2 3 5]


In [22]:
#boolean indexing
arr4 = np.array([1,2,3,4,5])
print(arr4[arr4 > 2])
print(arr4[arr4 % 2 == 0])

[3 4 5]
[2 4]


In [23]:
#slicing
arr = np.array([1,2,3,4,5])
print(arr[1:4])

[2 3 4]
