In [56]:
import numpy as np

In [57]:
#create - from list
arr1 = np.array([1,2,3,4,5])
print(arr1, type(arr1), arr1.shape, arr1.dtype)

arr2 = np.array([1,2,3, "array"])
print(arr2, type(arr2), arr2.shape, arr2.dtype)

arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2D, type(arr2D), arr2D.shape, arr2D.dtype)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,) int64
['1' '2' '3' 'array'] <class 'numpy.ndarray'> (4,) <U21
[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> (3, 3) int64


In [58]:
#create
arr1 = np.zeros((2,3), dtype=int)
print(arr1, type(arr1), arr1.shape, arr1.dtype)

arr2 = np.ones((5,), dtype=int)
print(arr2, type(arr2), arr2.shape, arr2.dtype)

arr3 =  np.full((3,3), fill_value= 2, dtype=int)
print(arr3, type(arr3), arr3.shape, arr3.dtype)

arr4 = np.eye(4, dtype=int)
print(arr4, type(arr4), arr4.shape, arr4.dtype)

arr5 = np.arange(1, 11, dtype=int)
print(arr5, type(arr5), arr5.shape, arr5.dtype)


arr6 = np.linspace(1, 10, 6, dtype=int)
print(arr6, type(arr6), arr6.shape, arr6.dtype)

[[0 0 0]
 [0 0 0]] <class 'numpy.ndarray'> (2, 3) int64
[1 1 1 1 1] <class 'numpy.ndarray'> (5,) int64
[[2 2 2]
 [2 2 2]
 [2 2 2]] <class 'numpy.ndarray'> (3, 3) int64
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]] <class 'numpy.ndarray'> (4, 4) int64
[ 1  2  3  4  5  6  7  8  9 10] <class 'numpy.ndarray'> (10,) int64
[ 1  2  4  6  8 10] <class 'numpy.ndarray'> (6,) int64
