In [20]:
import numpy as np

In [21]:
#aggregate functions
arr = np.array([1, 2, 3, 4, 5])
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.var(arr))

15
120
1
5
0
4
3.0
3.0
2.0


In [22]:
#power functions
arr = np.array([1, 2, 3, 4, 5])
print(np.square(arr))
print(np.sqrt(arr))
print(np.power(arr, 3))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [23]:
#log
arr = np.array([1, 2, 3, 4, 5])
print(np.log(arr))
print(np.log10(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [24]:
#rounding
print(np.round(3.52))
print(np.ceil(3.38))
print(np.floor(3.98))
print(np.trunc(3.98))

4.0
4.0
3.0
3.0
