In [1]:
import numpy as np

In [7]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
print(arr**2)
print(arr+2.5)
print(arr1 + arr2)

[ 1  4  9 16 25]
[3.5 4.5 5.5 6.5 7.5]
[ 7  9 11 13 15]
